apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iot-sensor-api-hpa
  namespace: autoscale-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-sensor-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
